### ISSUE TITLE
How can i reconstruction the point cloud to mesh?

### ISSUE THREAD

**Issue by kkwa999** [JohanYe/VF-Net#2]
Thanks for sharing your amazing project!
I have a question...
How did you reconstruct the point cloud to mesh?

There is no code to reconstruction the point cloud to mesh.
Could you tell me the method of reconstruction?

**Comment by JohanYe** [comment]
As per figure 2 of the paper, i simply pass a mesh grid through the decoder instead of the point encodings. I then use the same edges/facets to construct the final mesh.
These functions should provide a baseline for you to reproduce the meshes: 
https://github.com/JohanYe/VF-Net/blob/main/train_sampling.py#L325
https://github.com/JohanYe/VF-Net/blob/main/pc_utils.py#L364
https://github.com/JohanYe/VF-Net/blob/main/pc_utils.py#L344

**Comment by kkwa999** [comment]
@JohanYe Thank you.
